services:
  islasgeci:
    build:
      context: .
      dockerfile: Dockerfile
    image: islasgeci/maritime_informatics:latest
    command: bash
    volumes:
      - $PWD:/workdir
    depends_on:
      - postgis

  postgis:
    image: postgis/postgis
    container_name: marineinformatics-postgis
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
