services:
  islasgeci:
    build:
      context: .
      dockerfile: Dockerfile
    image: islasgeci/maritime_informatics:latest
    command: bash
    volumes:
      - $PWD:/workdir
    networks:
      - marineinformatics-network

  postgis:
    image: postgis/postgis
    container_name: marineinformatics-postgis
    environment:
      POSTGRES_PASSWORD: 4705
    networks:
      - marineinformatics-network

networks:
  marineinformatics-network:
    driver: bridge
