services:

  islasgeci:
    build:
      context: .
      dockerfile: Dockerfile
    image: islasgeci/maritime_informatics:latest
    container_name: maritime_informatics_ci
    command: bash
    stdin_open: true
    tty: true
    working_dir: /workdir
    volumes:
      - .:/workdir
    environment:
      - BITBUCKET_USERNAME
      - BITBUCKET_PASSWORD
    depends_on:
      postgis:
        condition: service_started
      data:
        condition: service_completed_successfully

  postgis:
    image: postgis/postgis
    container_name: maritime_informatics_postgis
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  data:
    image: islasgeci/maritime_informatics_data:latest
    volumes:
      - ./data/external:/data_container
    command: sh -c "mkdir --parents /data_container && cp --archive --verbose /data/. /data_container"
